export const menu = [
  {
    id: 1,
    title: "main",
    listItems: [
      {
        id: 1,
        title: "Homepage",
        url: "/",
        icon: "home.svg",
      },
      {
        id: 2,
        title: "Profile",
        url: "/users/1",
        icon: "user.svg",
      },
    ],
  },
  {
    id: 2,
    title: "lists",
    listItems: [
      {
        id: 1,
        title: "Users",
        url: "/users",
        icon: "user.svg",
      },
      {
        id: 2,
        title: "Products",
        url: "/products",
        icon: "product.svg",
      },
      {
        id: 3,
        title: "Orders",
        url: "/orders",
        icon: "order.svg",
      },
      {
        id: 4,
        title: "Posts",
        url: "/posts",
        icon: "post.svg",
      },
    ],
  },
  {
    id: 3,
    title: "general",
    listItems: [
      {
        id: 1,
        title: "Elements",
        url: "/",
        icon: "element.svg",
      },
      {
        id: 2,
        title: "Notes",
        url: "/",
        icon: "note.svg",
      },
      {
        id: 3,
        title: "Forms",
        url: "/",
        icon: "form.svg",
      },
      {
        id: 4,
        title: "Calendar",
        url: "/",
        icon: "calendar.svg",
      },
    ],
  },
  {
    id: 4,
    title: "Maintenance",
    listItems: [
      {
        id: 1,
        title: "Settings",
        url: "/",
        icon: "setting.svg",
      },
      {
        id: 2,
        title: "Backups",
        url: "/",
        icon: "backup.svg",
      },
    ],
  },
  {
    id: 5,
    title: "analytics",
    listItems: [
      {
        id: 1,
        title: "Charts",
        url: "/",
        icon: "chart.svg",
      },
      {
        id: 2,
        title: "Logs",
        url: "/",
        icon: "log.svg",
      },
    ],
  },
  {
    id: 6,
    title: "demo",
    listItems: [
      {
        id: 1,
        title: "Demo",
        url: "/demo",
        icon: "chart.svg",
      }
    ],
  },
];

export const topDealUsers = [
  {
    id: 1,
    img: "https://randomuser.me/api/portraits/men/30.jpg",
    username: "Alexander Moore",
    email: "alexander.moore@gmail.com",
    amount: "8,374",
  },
  {
    id: 2,
    img: "https://randomuser.me/api/portraits/men/22.jpg",
    username: "James Oliver",
    email: "james.oliver@gmail.com",
    amount: "4,732",
  },
  {
    id: 3,
    img: "https://randomuser.me/api/portraits/women/23.jpg",
    username: "Ava Johnson",
    email: "ava.johnson@gmail.com",
    amount: "2,983",
  },
  {
    id: 4,
    img: "https://randomuser.me/api/portraits/men/24.jpg",
    username: "Liam Brown",
    email: "liam.brown@gmail.com",
    amount: "5,123",
  },
  {
    id: 5,
    img: "https://randomuser.me/api/portraits/women/25.jpg",
    username: "Sophia Garcia",
    email: "sophia.garcia@gmail.com",
    amount: "3,451",
  },
  {
    id: 6,
    img: "https://randomuser.me/api/portraits/men/26.jpg",
    username: "Noah Martinez",
    email: "noah.martinez@gmail.com",
    amount: "6,278",
  },
  {
    id: 7,
    img: "https://randomuser.me/api/portraits/women/27.jpg",
    username: "Mia Clark",
    email: "mia.clark@gmail.com",
    amount: "1,897",
  },
  {
    id: 8,
    img: "https://randomuser.me/api/portraits/men/28.jpg",
    username: "William Anderson",
    email: "william.anderson@gmail.com",
    amount: "7,540",
  },
  {
    id: 9,
    img: "https://randomuser.me/api/portraits/women/29.jpg",
    username: "Isabella Lee",
    email: "isabella.lee@gmail.com",
    amount: "2,652",
  }
];

export const chartBoxUser = {
  color: "#8884d8",
  icon: "/userIcon.svg",
  title: "Total Users",
  number: "11.238",
  dataKey: "users",
  percentage: 45,
  chartData: [
    { name: "Sun", users: 400 },
    { name: "Mon", users: 600 },
    { name: "Tue", users: 500 },
    { name: "Wed", users: 700 },
    { name: "Thu", users: 400 },
    { name: "Fri", users: 500 },
    { name: "Sat", users: 450 },
  ],
};

export const chartBoxProduct = {
  color: "skyblue",
  icon: "/productIcon.svg",
  title: "Total Products",
  number: "238",
  dataKey: "products",
  percentage: 21,
  chartData: [
    { name: "Sun", products: 400 },
    { name: "Mon", products: 600 },
    { name: "Tue", products: 500 },
    { name: "Wed", products: 700 },
    { name: "Thu", products: 400 },
    { name: "Fri", products: 500 },
    { name: "Sat", products: 450 },
  ],
};
export const chartBoxRevenue = {
  color: "teal",
  icon: "/revenueIcon.svg",
  title: "Total Revenue",
  number: "$56.432",
  dataKey: "revenue",
  percentage: -12,
  chartData: [
    { name: "Sun", revenue: 400 },
    { name: "Mon", revenue: 600 },
    { name: "Tue", revenue: 500 },
    { name: "Wed", revenue: 700 },
    { name: "Thu", revenue: 400 },
    { name: "Fri", revenue: 500 },
    { name: "Sat", revenue: 450 },
  ],
};
export const chartBoxConversion = {
  color: "gold",
  icon: "/conversionIcon.svg",
  title: "Total Ratio",
  number: "2.6",
  dataKey: "ratio",
  percentage: 12,
  chartData: [
    { name: "Sun", ratio: 400 },
    { name: "Mon", ratio: 600 },
    { name: "Tue", ratio: 500 },
    { name: "Wed", ratio: 700 },
    { name: "Thu", ratio: 400 },
    { name: "Fri", ratio: 500 },
    { name: "Sat", ratio: 450 },
  ],
};

export const barChartBoxRevenue = {
  title: "Profit Earned",
  color: "#8884d8",
  dataKey: "profit",
  chartData: [
    {
      name: "Sun",
      profit: 4000,
    },
    {
      name: "Mon",
      profit: 3000,
    },
    {
      name: "Tue",
      profit: 2000,
    },
    {
      name: "Wed",
      profit: 2780,
    },
    {
      name: "Thu",
      profit: 1890,
    },
    {
      name: "Fri",
      profit: 2390,
    },
    {
      name: "Sat",
      profit: 3490,
    },
  ],
};

export const barChartBoxVisit = {
  title: "Total Visit",
  color: "#FF8042",
  dataKey: "visit",
  chartData: [
    {
      name: "Sun",
      visit: 4000,
    },
    {
      name: "Mon",
      visit: 3000,
    },
    {
      name: "Tue",
      visit: 2000,
    },
    {
      name: "Wed",
      visit: 2780,
    },
    {
      name: "Thu",
      visit: 1890,
    },
    {
      name: "Fri",
      visit: 2390,
    },
    {
      name: "Sat",
      visit: 3490,
    },
  ],
};

export const userRows = [
  {
    id: 1,
    img: "https://randomuser.me/api/portraits/men/20.jpg",
    lastName: "Baker",
    firstName: "Logan",
    email: "logan.baker@gmail.com",
    phone: "753 159 486",
    createdAt: "30.01.2024",
    verified: true,
  },
  {
    id: 2,
    img: "https://randomuser.me/api/portraits/men/2.jpg",
    lastName: "Smith",
    firstName: "John",
    email: "john.smith@gmail.com",
    phone: "987 654 321",
    createdAt: "15.03.2023",
    verified: false,
  },
  {
    id: 3,
    img: "https://randomuser.me/api/portraits/women/3.jpg",
    lastName: "Brown",
    firstName: "Emma",
    email: "emma.brown@gmail.com",
    phone: "456 789 123",
    createdAt: "20.01.2023",
    verified: true,
  },
  {
    id: 4,
    img: "https://randomuser.me/api/portraits/men/4.jpg",
    lastName: "Johnson",
    firstName: "James",
    email: "james.johnson@gmail.com",
    phone: "789 123 456",
    createdAt: "05.06.2023",
    verified: false,
  },
  {
    id: 5,
    img: "https://randomuser.me/api/portraits/women/5.jpg",
    lastName: "Garcia",
    firstName: "Sophia",
    email: "sophia.garcia@gmail.com",
    phone: "321 654 987",
    createdAt: "12.07.2023",
    verified: true,
  },
  {
    id: 6,
    img: "https://randomuser.me/api/portraits/men/6.jpg",
    lastName: "Martinez",
    firstName: "David",
    email: "david.martinez@gmail.com",
    phone: "654 987 321",
    createdAt: "30.08.2023",
    verified: false,
  },
  {
    id: 7,
    img: "https://randomuser.me/api/portraits/women/7.jpg",
    lastName: "Clark",
    firstName: "Mia",
    email: "mia.clark@gmail.com",
    phone: "159 753 486",
    createdAt: "19.04.2023",
    verified: true,
  },
  {
    id: 8,
    img: "https://randomuser.me/api/portraits/men/8.jpg",
    lastName: "Lewis",
    firstName: "Michael",
    email: "michael.lewis@gmail.com",
    phone: "753 486 159",
    createdAt: "11.02.2023",
    verified: true,
  },
  {
    id: 9,
    img: "https://randomuser.me/api/portraits/women/9.jpg",
    lastName: "Robinson",
    firstName: "Olivia",
    email: "olivia.robinson@gmail.com",
    phone: "852 369 741",
    createdAt: "22.05.2023",
    verified: false,
  },
  {
    id: 10,
    img: "https://randomuser.me/api/portraits/men/10.jpg",
    lastName: "Walker",
    firstName: "Ethan",
    email: "ethan.walker@gmail.com",
    phone: "963 741 852",
    createdAt: "08.03.2023",
    verified: true,
  },
  {
    id: 11,
    img: "https://randomuser.me/api/portraits/women/11.jpg",
    lastName: "Hall",
    firstName: "Ava",
    email: "ava.hall@gmail.com",
    phone: "321 789 654",
    createdAt: "10.04.2023",
    verified: true,
  },
  {
    id: 12,
    img: "https://randomuser.me/api/portraits/men/12.jpg",
    lastName: "Allen",
    firstName: "Daniel",
    email: "daniel.allen@gmail.com",
    phone: "456 123 789",
    createdAt: "15.05.2023",
    verified: false,
  },
  {
    id: 13,
    img: "https://randomuser.me/api/portraits/women/13.jpg",
    lastName: "Young",
    firstName: "Emily",
    email: "emily.young@gmail.com",
    phone: "654 321 987",
    createdAt: "25.06.2023",
    verified: true,
  },
  {
    id: 14,
    img: "https://randomuser.me/api/portraits/men/14.jpg",
    lastName: "King",
    firstName: "Alexander",
    email: "alexander.king@gmail.com",
    phone: "789 456 123",
    createdAt: "09.07.2023",
    verified: true,
  },
  {
    id: 15,
    img: "https://randomuser.me/api/portraits/women/15.jpg",
    lastName: "Wright",
    firstName: "Lily",
    email: "lily.wright@gmail.com",
    phone: "123 987 654",
    createdAt: "17.08.2023",
    verified: false,
  },
  {
    id: 16,
    img: "https://randomuser.me/api/portraits/men/16.jpg",
    lastName: "Lopez",
    firstName: "Matthew",
    email: "matthew.lopez@gmail.com",
    phone: "741 852 963",
    createdAt: "14.09.2023",
    verified: true,
  },
  {
    id: 17,
    img: "https://randomuser.me/api/portraits/women/17.jpg",
    lastName: "Scott",
    firstName: "Isabella",
    email: "isabella.scott@gmail.com",
    phone: "963 852 741",
    createdAt: "03.10.2023",
    verified: false,
  },
  {
    id: 18,
    img: "https://randomuser.me/api/portraits/men/18.jpg",
    lastName: "Green",
    firstName: "Lucas",
    email: "lucas.green@gmail.com",
    phone: "852 963 741",
    createdAt: "18.11.2023",
    verified: true,
  },
  {
    id: 19,
    img: "https://randomuser.me/api/portraits/women/19.jpg",
    lastName: "Adams",
    firstName: "Mason",
    email: "mason.adams@gmail.com",
    phone: "159 753 486",
    createdAt: "28.12.2023",
    verified: false,
  }
];

export const products = [
  {
    id: 1,
    img: "https://store.sony.com.au/on/demandware.static/-/Sites-sony-master-catalog/default/dw1b537bbb/images/PLAYSTATION5W/PLAYSTATION5W.png",
    title: "Playstation 5 Digital Edition",
    color: "white",
    producer: "Sony",
    price: "$250.99",
    createdAt: "01.02.2023",
    inStock: true,
  },
  {
    id: 2,
    img: "https://www.pngmart.com/files/6/Dell-Laptop-PNG-Image.png",
    title: "Dell Laptop KR211822",
    color: "black",
    producer: "Dell",
    price: "$499.99",
    createdAt: "01.02.2023",
    inStock: true,
  },
  {
    id: 3,
    img: "http://images.samsung.com/is/image/samsung/uk-led-tv-hg40ed670ck-hg40ed670ckxxu-001-front",
    title: "Samsung TV 4K SmartTV",
    color: "gray",
    producer: "Samsung",
    price: "$999.49",
    createdAt: "01.02.2023",
    inStock: true,
  },
  {
    id: 4,
    img: "https://raylo.imgix.net/iphone-14-blue.png",
    title: "Apple Iphone 14 Pro Max",
    color: "white",
    producer: "Apple",
    price: "$799.49",
    createdAt: "01.02.2023",
    inStock: true,
  },
  {
    id: 5,
    img: "https://www.signify.com/b-dam/signify/en-aa/about/news/2020/20200903-movie-night-essentials-popcorn-ice-cream-and-the-new-philips-hue-play-gradient-lightstrip/packaging-lighstrip.png",
    title: "Philips Hue Play Gradient",
    color: "rainbow",
    producer: "Philips",
    price: "$39.99",
    createdAt: "01.02.2023",
  },
  {
    id: 6,
    img: "https://www.smartworld.it/wp-content/uploads/2019/09/High_Resolution_PNG-MX-Master-3-LEFT-GRAPHITE.png",
    title: "Logitech MX Master 3",
    color: "black",
    producer: "Logitech",
    price: "$59.49",
    createdAt: "01.02.2023",
    inStock: true,
  },
  {
    id: 7,
    img: "https://www.pngarts.com/files/7/Podcast-Mic-PNG-Picture.png",
    title: "Rode Podcast Microphone",
    color: "gray",
    producer: "Rode",
    price: "$119.49",
    createdAt: "01.02.2023",
  },
  {
    id: 8,
    img: "https://5.imimg.com/data5/SW/VM/MY-5774620/toshiba-split-ac-2-ton-3-star-rated-ras-24s3ks-500x500.png",
    title: "Toshiba Split AC 2",
    color: "white",
    producer: "Toshiba",
    price: "$899.99",
    createdAt: "01.02.2023",
    inStock: true,
  },
  {
    id: 9,
    img: "https://img.productz.com/review_image/102489/preview_sony-kdl-50w800b-50-inch-hdtv-review-superb-picture-102489.png",
    title: "Sony Bravia KDL-47W805A",
    color: "black",
    producer: "Sony",
    price: "$970.49",
    createdAt: "01.02.2023",
  },
  {
    id: 10,
    img: "https://venturebeat.com/wp-content/uploads/2015/07/As_AO1-131_gray_nonglare_win10_03.png?fit=1338%2C1055&strip=all",
    title: "Acer Laptop 16 KL-4804",
    color: "black",
    producer: "Acer",
    price: "$599.99",
    createdAt: "01.02.2023",
    inStock: true,
  },
];

export const orders = [
  {
    id: 1,
    img: "https://store.sony.com.au/on/demandware.static/-/Sites-sony-master-catalog/default/dw1b537bbb/images/PLAYSTATION5W/PLAYSTATION5W.png",
    title: "Playstation 5 Digital Edition",
    color: "white",
    producer: "Sony",
    price: "$250.99",
    createdAt: "01.02.2023",
    inStock: true,
  },
  {
    id: 2,
    img: "https://www.pngmart.com/files/6/Dell-Laptop-PNG-Image.png",
    title: "Dell Laptop KR211822",
    color: "black",
    producer: "Dell",
    price: "$499.99",
    createdAt: "01.02.2023",
    inStock: true,
  },
  {
    id: 3,
    img: "http://images.samsung.com/is/image/samsung/uk-led-tv-hg40ed670ck-hg40ed670ckxxu-001-front",
    title: "Samsung TV 4K SmartTV",
    color: "gray",
    producer: "Samsung",
    price: "$999.49",
    createdAt: "01.02.2023",
    inStock: true,
  },
  {
    id: 4,
    img: "https://raylo.imgix.net/iphone-14-blue.png",
    title: "Apple Iphone 14 Pro Max",
    color: "white",
    producer: "Apple",
    price: "$799.49",
    createdAt: "01.02.2023",
    inStock: true,
  },
  {
    id: 5,
    img: "https://www.signify.com/b-dam/signify/en-aa/about/news/2020/20200903-movie-night-essentials-popcorn-ice-cream-and-the-new-philips-hue-play-gradient-lightstrip/packaging-lighstrip.png",
    title: "Philips Hue Play Gradient",
    color: "rainbow",
    producer: "Philips",
    price: "$39.99",
    createdAt: "01.02.2023",
  },
  {
    id: 6,
    img: "https://www.smartworld.it/wp-content/uploads/2019/09/High_Resolution_PNG-MX-Master-3-LEFT-GRAPHITE.png",
    title: "Logitech MX Master 3",
    color: "black",
    producer: "Logitech",
    price: "$59.49",
    createdAt: "01.02.2023",
    inStock: true,
  },
  {
    id: 7,
    img: "https://www.pngarts.com/files/7/Podcast-Mic-PNG-Picture.png",
    title: "Rode Podcast Microphone",
    color: "gray",
    producer: "Rode",
    price: "$119.49",
    createdAt: "01.02.2023",
  },
  {
    id: 8,
    img: "https://5.imimg.com/data5/SW/VM/MY-5774620/toshiba-split-ac-2-ton-3-star-rated-ras-24s3ks-500x500.png",
    title: "Toshiba Split AC 2",
    color: "white",
    producer: "Toshiba",
    price: "$899.99",
    createdAt: "01.02.2023",
    inStock: true,
  },
  {
    id: 9,
    img: "https://img.productz.com/review_image/102489/preview_sony-kdl-50w800b-50-inch-hdtv-review-superb-picture-102489.png",
    title: "Sony Bravia KDL-47W805A",
    color: "black",
    producer: "Sony",
    price: "$970.49",
    createdAt: "01.02.2023",
  },
  {
    id: 10,
    img: "https://venturebeat.com/wp-content/uploads/2015/07/As_AO1-131_gray_nonglare_win10_03.png?fit=1338%2C1055&strip=all",
    title: "Acer Laptop 16 KL-4804",
    color: "black",
    producer: "Acer",
    price: "$599.99",
    createdAt: "01.02.2023",
    inStock: true,
  },
];

// id: 3,
// img: "https://randomuser.me/api/portraits/women/3.jpg",
// lastName: "Brown",
// firstName: "Emma",
// email: "emma.brown@gmail.com",
// phone: "456 789 123",
// createdAt: "20.01.2023",
// verified: true,

export const singleUser = {
  id: 1,
  title: "Emma Brown",
  img: "https://randomuser.me/api/portraits/women/3.jpg",
  info: {
    username: "emmabrown",
    fullname: "Emma Brown",
    email: "emma.brown@gmail.com",
    phone: "456 789 123",
    status: "verified",
  },
  chart: {
    dataKeys: [
      { name: "visits", color: "#82ca9d" },
      { name: "clicks", color: "#8884d8" },
    ],
    data: [
      {
        name: "Sun",
        visits: 4000,
        clicks: 2400,
      },
      {
        name: "Mon",
        visits: 3000,
        clicks: 1398,
      },
      {
        name: "Tue",
        visits: 2000,
        clicks: 3800,
      },
      {
        name: "Wed",
        visits: 2780,
        clicks: 3908,
      },
      {
        name: "Thu",
        visits: 1890,
        clicks: 4800,
      },
      {
        name: "Fri",
        visits: 2390,
        clicks: 3800,
      },
      {
        name: "Sat",
        visits: 3490,
        clicks: 4300,
      },
    ],
  },
  activities: [
    {
      text: "Emma Brown purchased Playstation 5 Digital Edition",
      time: "3 day ago",
    },
    {
      text: "Emma Brown added 3 items into their wishlist",
      time: "1 week ago",
    },
    {
      text: "Emma Brown purchased Sony Bravia KD-32w800",
      time: "2 weeks ago",
    },
    {
      text: "Emma Brown reviewed a product",
      time: "1 month ago",
    },
    {
      text: "Emma Brown added 1 items into their wishlist",
      time: "1 month ago",
    },
    {
      text: "Emma Brown reviewed a product",
      time: "2 months ago",
    },
  ],
};
export const singleProduct = {
  id: 1,
  title: "Playstation 5 Digital Edition",
  img: "https://store.sony.com.au/on/demandware.static/-/Sites-sony-master-catalog/default/dw1b537bbb/images/PLAYSTATION5W/PLAYSTATION5W.png",
  info: {
    productId: "Ps5SDF1156d",
    color: "white",
    price: "$250.99",
    producer: "Sony",
    export: "Japan",
  },
  chart: {
    dataKeys: [
      { name: "visits", color: "#82ca9d" },
      { name: "orders", color: "#8884d8" },
    ],
    data: [
      {
        name: "Sun",
        visits: 4000,
        orders: 2400,
      },
      {
        name: "Mon",
        visits: 3000,
        orders: 1398,
      },
      {
        name: "Tue",
        visits: 2000,
        orders: 3800,
      },
      {
        name: "Wed",
        visits: 2780,
        orders: 3908,
      },
      {
        name: "Thu",
        visits: 1890,
        orders: 4800,
      },
      {
        name: "Fri",
        visits: 2390,
        orders: 3800,
      },
      {
        name: "Sat",
        visits: 3490,
        orders: 4300,
      },
    ],
  },
  activities: [
    {
      text: "Emma Brown purchased Playstation 5 Digital Edition",
      time: "3 day ago",
    },
    {
      text: "Jane Doe added Playstation 5 Digital Edition into their wishlist",
      time: "1 week ago",
    },
    {
      text: "Mike Doe purchased Playstation 5 Digital Edition",
      time: "2 weeks ago",
    },
    {
      text: "Anna Doe reviewed the product",
      time: "1 month ago",
    },
    {
      text: "Michael Doe added Playstation 5 Digital Edition into their wishlist",
      time: "1 month ago",
    },
    {
      text: "Helen Doe reviewed the product",
      time: "2 months ago",
    },
  ],
};
